name: Demo name
run-name: ${{ github.actor }} 
on: [workflow_dispatch]
jobs:
  some-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: "echo Hello ${{ github.actor }}"
      - name: Check node version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Display node version
        run: node -v